### PR TITLE
fix: removing normalize css

### PR DESCRIPTION
**Pull request by bclark-p44**
Closes # 

## 📝 Description

Normalize is causing issues in some of our products, going to revert and work with the teams to address any concerns with CSS normalization.

## Screenshots

> Please provide screenshots for any visual changes

## Merge checklist

- [ ] Added/updated tests
- [x] Added changeset

### CODE REVIEW

**Comment by daniel-p44** [comment]
I'd be okay with just having the normalization off by default with the option to turn it on via that prop you mentioned.

**Comment by bclark-p44** [comment]
Let's talk more about what we want and don't want to normalize. In a follow up major version. I should have really tagged this change as a major release.

**Comment by bclark-p44** [comment]
Let's talk more about what we want and don't want to normalize. In a follow up major version. I should have really tagged this change as a major release.

**Comment by daniel-p44** [comment]
> Let's talk more about what we want and don't want to normalize. In a follow up major version. I should have really tagged this change as a major release.

Works for me!

**Pull request merged**
